export default [
  {
    country: 'Algeria',
    lastElection: '04 May 2017',
    women: 25.8,
    singleHouse: false,
  },
  {
    country: 'Bahrain',
    lastElection: '01 December 2018',
    women: 15.0,
    singleHouse: false,
  },
  {
    country: 'Egypt',
    lastElection: '17 October 2015',
    women: 14.9,
    singleHouse: true,
  },
  {
    country: 'Iraq',
    lastElection: '12 May 2018',
    women: 25.2,
    singleHouse: true,
  },
  {
    country: 'Israel',
    lastElection: '17 March 2015',
    women: 29.2,
    singleHouse: true,
  },
  {
    country: 'Jordan',
    lastElection: '20 September 2016',
    women: 15.4,
    singleHouse: false,
  },
  {
    country: 'Kuwait',
    lastElection: '26 November 2016',
    women: 4.6,
    singleHouse: true,
  },
  {
    country: 'Lebanon',
    lastElection: '06 May 2018',
    women: 4.7,
    singleHouse: true,
  },
  {
    country: 'Libya',
    lastElection: '25 June 2014',
    women: 16.0,
    singleHouse: true,
  },
  {
    country: 'Mauritania',
    lastElection: '01 September 2018',
    women: 20.3,
    singleHouse: true,
  },
  {
    country: 'Morocco',
    lastElection: '07 October 2016',
    women: 20.5,
    singleHouse: false,
  },
  {
    country: 'Oman',
    lastElection: '25 October 2015',
    women: 1.2,
    singleHouse: false,
  },
  {
    country: 'Qatar',
    lastElection: '01 July 2013',
    women: 9.8,
    singleHouse: true,
  },
  {
    country: 'Saudi Arabia',
    lastElection: '02 December 2016',
    women: 19.9,
    singleHouse: true,
  },
  {
    country: 'Sudan',
    lastElection: '13 April 2015',
    women: 27.7,
    singleHouse: false,
  },
  {
    country: 'Syria',
    lastElection: '13 April 2016',
    women: 13.2,
    singleHouse: true,
  },
  {
    country: 'Tunisia',
    lastElection: '26 October 2014',
    women: 35.9,
    singleHouse: true,
  },
  {
    country: 'United Arab Emirates',
    lastElection: '03 October 2015',
    women: 22.5,
    singleHouse: true,
  },
  {
    country: 'Yemen',
    lastElection: '27 April 2003',
    women: 0.3,
    singleHouse: false,
  },
];
